### ISSUE TITLE
Add settings for sqlite to speed up development.

### ISSUE THREAD

**Issue by kennedyshead** [pebble-dev/rebblestore-api-python#9]
If there are no custom postgresql-queries that need to be done its far easier to use sqlite in development.

**Comment by bbenne10** [comment]
There are custom queries though. The full-text queries are all custom (and can't be replicated in sqlalchemy, if I'm not mistaken)

**Comment by bbenne10** [comment]
Excuse me...sqllite3. Sorry about that.

**Comment by kennedyshead** [comment]
Yes if there is fulltext search there is nothing to do, if its not rewritten to use wosh, Solr or something similar.

**Comment by bbenne10** [comment]
Frankly, I find ElasticSearch and solr to be a huge pain to manage on large
datasets and the PGSQL solution is simple to upkeep for smaller solutions.
Given the difficulties I have had in the past with attempting to use
differemt dbs for prod and development, installing and running PostgreSQL
is likely to stay as a dependency for the foreseeable future.

**Comment by kennedyshead** [comment]
I have implemented both solr and woosh and found pretty straightforward but for simplicity I do agree that pgsql would be the best route @ this point

**Comment by bbenne10** [comment]
Woosh looks interesting (and is still on my radar for another project), but simplicity dictates that when one tool works for a job, why use two? :P 

If we find that our scalability is affected by this decision, I'm more than happy to re-look at these avenues.

**Comment by kennedyshead** [comment]
Agreed! And woosh is really nice 👍

**Comment by kennedyshead** [comment]
And just for future reference I would say that to make it possible to run tests and so on without the postgres requirement this would be a great idea.

**Comment by bbenne10** [comment]
Yes - that's a great point. I do prefer that, but it limits how deeply you can use the power of a particular backend (for instance, can't use the `TSVector` stuff without PostgreSQL but the only reason I wanted to go with a SQL solution was the `TSVector` stuff, as I'd have used Mongo otherwise)
